name: Build Debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Debug Keystore
      run: |
        echo "MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFHhmhgjBgg6xDvdXbkNLGM2LbkuKAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQSurF5t8SfDBwYgLkpZ//3QSCBNDPqSdBaI8VkkNsuNxi98rDtYDk48mbym68QoipUG4vnWcCt+E6PPnz8x+l+oymyRUnFBRJsXGG6KltZ5CevIBucP2fP/ER9AF5LDmk/uHpY9WSawnnTmoR1/h0uelf9yFByoUWdASjLurlX9uxpVrO99Es+VfK0qnjt5BCDL8AQK7FzUi/vTotQ2CvbsU2Cd+JBbn63CPqSywGelI8tYOwD3hqwdeWzGdSDlOV48looCn+nUJxN5GJW59T8ogCyjqRhSssOkkMwT6wMXAZKpA+xSDDblGNRFc3iDiVtdM3+sR7dMA+M1mZCldoXM3RYKTF3qQ0fHsnmvjLHV3b01y0Ze9okJufUrpVh/9zYZzmQDJNfpt7OKvbJC10j5HeX7VdnKl2uwmGRZfVUnTD/GU+RlpAkcYT+dztBC7gUSUqg3rND6JEbQxKn73EwheEbjV8gK5TdN8QoStfXFA8W/e295v8L+qH2bpndkd8Uqln+6wQWAUC0cnzSS6F3pxKtLnQbHqdfPhxKvLhCr3CAgEBup5VGdQshnTlb4mbBoZyHHDRNLU9l8bsBLxORQq3r5FFxUUV7jPCZGogb5LcE+uOF8vQ4UiP797mmHThfJecivw3GdG7tVTfMYJJuhEEUCk6S7dNORD95O3bxL3JinTN5+AgL/2pF/vVQ1M4onJT8xvOzh0wB85vxR4o12QYgsx30f4jdI/o1FdH15rQ3TRVbX4DQPjLlu16tCUHPslZ6CDzEDRSM9xCY4PjAFaAE1rmKTh1AubCsmbBP4BVhPjl+rVCl6gy0eqeRYgnwoWyZS3pprWNx7lOqjQyooOAyuSQLTjvvJK0qWfnhUVMWlDsyuFeoEiGldlnRCCQ+zOINZimbCbCfI/cJCkX77C+7Hq+mL5mYbI2UytrOVHZSVLohXoULZyL4ncVZLLd6LKmzp2Lku1zEtg+Q+YprheGYoH2GNWCAg0k9MPy2gJlZCBiEADJp86YsTY1BAKNEWYCA+Ssf0aogT8HLiv6mbvYlavBa6Ir+Rupkd/g194cKyn6ORHUI9VTw1nT9ctlo0GTcd5n8MrbzORk3l8cd2pK0/iQs+9ng/TOrIxEx0Yqd7smQOekFsJoBLl3MuHbry0vFVhEopYxVDkiq8Dn2k7iPUtF3td3E8I+F/R72WlVlav8a5xyku+gEro60BZdypSod0/CdDmPPGu4QAXqy80bdtsbrcgibRiJ8f/cvp7PzJIfCRDP2N1psiaCXJJHN6CZMp1uWSi207CwGUNQkORHb5F7I+Qgp9OK0IY3T2PdoL8wwnQyh6vm0uEKiWO+FSn9WPwAahksJ8BlToAR587ToJnQGWTLvJamm2xWrIEi3g5k8AZ/SlnbIGpRWzvRE3q2G/CVS2exdnn2IDjCvTWJVaeEp4NZSttEKp58k/fGJHLROUPFtQbBEHUMiE/4n53ZGSDstruNS82id9TsXovgTLfJIEd6emSiGf5VpaNYAq5Wc+jLMl8UQMmyoAMxWCtZrv7o/Lrr9c40cdbkX4MRynC2BpF28bk4dYRLfIosiGuik/a1axBplVz65f/iL7JNwjHNituEWtk0Qqh1Igh/nB3elx0+OGbEU3rSopI0kgw4KJ22iHC/Ipek3aE2ifOepzFSMC0GCSqGSIb3DQEJFDEgHh4AYQBuAGQAcgBvAGkAZABkAGUAYgB1AGcAawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4MjMyMTUwNzU0NjCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQGUdSDVBdlmDfj82xKa9uslmujaQICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEDs6qstBaH+/iV0eTRbZyr6AggOgNuKOvVPZlKASp9RVWcbqg8Mhtigw2NtgzYQk3SOsPD66i1ZbiyZ7zx1XGnZu+x5DyKwypqTHBVdfufsUz75TzFeHMx16h99UnU3hdmCC+JUqOZx2slJeAN+YR3B5EukyS9AL4acXQAsujRNSSzP35kKlp7vV+EqiMe82yk1/OxxMsY7L1HzRdSdalxd7GyiQzg970kDdKQflEMzhKjS21AfUwnozptkzg6M/QGyQ/idaql7h7HZo4Pm6vQ7sRSgo7oxKSRoEQSg6tL52WUgwFVdda8SgF110wI5nYzo+XfF5nV0ts8Vdk5fDmBc23shJD9/8fytL/OzhoGDogI8uY4J+U+LveDMed+QBBwC0Ulj+2rz1JOcyst41FIpKQxzxPXctPnbLM7Fd3A8rqb56nwXGDWXr6Ifdwu1f4ojGNeE6MgDq8ZRurC3E9+XojrUHH06oMTXs4C4YjCAW1Kzk39+o26xKW/Q9ydLdBi8HNNpKG8KZEk9wnMYzp6am/u1VYZsWPnAZw3/7HXuI6DpQiVMzs6TPQdmf1N6s/HGHcDard1jjCHJYj/eNM4bRyp/7b48FtgGX+2hlEvuTbK4R25a0aVwcVrRqoC02fTyj7r8a2mnckhdRgHPgcl7gop40IiRtd4kp2o44wfnbi69CiHgnqwYTYU7gaWblldV4ZeZkjYCMYAf4cmnatAt2aol/as5ESa9i+OER3uSL/gl1AK+juUDi3lGjGlzzMVQ78krDxV44d1XNU0C/R0p/x/19+8SDj0+9vaTBddCyVsQ5Cr7HAp6u2PV+5wrYc45HeNOGBHeJW2+mYVjn1jhD0fh2NCs3tcdYaZpSaSXFiTmtavYI8e+iucMLJ4Nrji8XXQKThNwG3Wn5Ny8t4+P4F7WgbV7EaB472BOvZyt2mjQD4YlnEYakzvZCjeBe0BIw/CCxjePWIaIaG00cY4AciRLKoMjwVW8LXAa7YrwRUD9SS5kfVFRqXYhpZeYVS2YPDhdp59wXOYO9uw8y4bRd30uhgN5QTzJOKE0xIJTaTRx5ThWXxBnAjFJt6TQespaWky4oBeC1qP5xEeEGuUkabV2maa6Xrb7g2p/AApFlvXfMnD+s1LH29MV+7siEusvfNXwKq3VTQETPAxgpi2TkJ0xVa2lnpp6AFZbRsLmUpRH2tvkwpO6L9uNGIM8AmrfgyIem0Ensu1KvkLNFD89q1yT0DxpmaSj4YvIqiS4zgHT25zBNMDEwDQYJYIZIAWUDBAIBBQAEIDApY4gGmGsvMV6qUfkN5dHwcnxqe25M7UkjRyl6PuzeBBQIAaS6Pe6Em3LRKBclOFoSZ4Wb7AICJxA=" | base64 --decode > debug.keystore

    - name: Create .env file
      run: |
        echo "TURSO_DB_URL=${{ secrets.TURSO_DB_URL }}" >> .env
        echo "TURSO_READ_TOKEN=${{ secrets.TURSO_READ_TOKEN }}" >> .env

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
